server:
  port: 8080
spring:
  sql:
    init:
      mode: never
  devtools:
      livereload:
          enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/category;MODE=MySQL
    username: root
    password: root
    driver-class-name: org.h2.Driver
    hikari:
      connectionTimeout: 5000
      validationTimeout: 1000
      maximumPoolSize: 10
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

decorator:
  datasource:
    p6spy:
      enable-logging: true
